// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AddRoleRequest
 *
 * Assigner un rôle supplémentaire à un utilisateur déjà membre (ou connu par email).
 */
export type AddRoleRequest = {
    /**
     * Email
     */
    email: string;
    role: RoleEnum;
};

/**
 * AdminCreateClubRequest
 */
export type AdminCreateClubRequest = {
    /**
     * Club Name
     */
    club_name: string;
    /**
     * Sport
     */
    sport?: string;
    /**
     * Admin First Name
     */
    admin_first_name: string;
    /**
     * Admin Last Name
     */
    admin_last_name: string;
    /**
     * Admin Email
     */
    admin_email: string;
};

/**
 * AdminCreateClubResponse
 */
export type AdminCreateClubResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Sport
     */
    sport: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Admin User Id
     */
    admin_user_id: string;
    /**
     * Admin Email
     */
    admin_email: string;
    /**
     * Generated Password
     */
    generated_password: string;
};

/**
 * AdminUpdateClubRequest
 */
export type AdminUpdateClubRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Sport
     */
    sport?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * AgeCategoryEnum
 *
 * Catégories d'âge type fédérations (U = under).
 */
export type AgeCategoryEnum = 'U7' | 'U9' | 'U11' | 'U13' | 'U15' | 'U17' | 'U19' | 'U21' | 'SENIOR' | 'OTHER';

/**
 * AthleteProfileResponse
 */
export type AthleteProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    /**
     * Age
     */
    age?: number | null;
    gender?: GenderEnum | null;
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Second Nationality Code
     */
    second_nationality_code?: string | null;
    /**
     * Place Of Birth
     */
    place_of_birth?: string | null;
    /**
     * Country Of Birth Code
     */
    country_of_birth_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Weight Kg
     */
    weight_kg?: number | null;
    dominant_side?: DominantSideEnum | null;
    blood_type?: BloodTypeEnum | null;
    /**
     * Jersey Number
     */
    jersey_number?: number | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Position Group
     */
    position_group?: string | null;
    /**
     * Secondary Position
     */
    secondary_position?: string | null;
    /**
     * Federation License Number
     */
    federation_license_number?: string | null;
    /**
     * Federation Name
     */
    federation_name?: string | null;
    /**
     * License Expires At
     */
    license_expires_at?: string | null;
    /**
     * Emergency Contact Name
     */
    emergency_contact_name?: string | null;
    /**
     * Emergency Contact Phone
     */
    emergency_contact_phone?: string | null;
    /**
     * Emergency Contact Relationship
     */
    emergency_contact_relationship?: string | null;
    /**
     * School Name
     */
    school_name?: string | null;
    /**
     * School Level
     */
    school_level?: string | null;
    /**
     * Academic Workload Note
     */
    academic_workload_note?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Minor
     */
    is_minor?: boolean | null;
    /**
     * Requires Parental Consent Strict
     */
    requires_parental_consent_strict?: boolean | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AthleteProfileUpdate
 */
export type AthleteProfileUpdate = {
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    gender?: GenderEnum | null;
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Second Nationality Code
     */
    second_nationality_code?: string | null;
    /**
     * Place Of Birth
     */
    place_of_birth?: string | null;
    /**
     * Country Of Birth Code
     */
    country_of_birth_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Weight Kg
     */
    weight_kg?: number | null;
    dominant_side?: DominantSideEnum | null;
    blood_type?: BloodTypeEnum | null;
    /**
     * Jersey Number
     */
    jersey_number?: number | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Position Group
     */
    position_group?: string | null;
    /**
     * Secondary Position
     */
    secondary_position?: string | null;
    /**
     * Federation License Number
     */
    federation_license_number?: string | null;
    /**
     * Federation Name
     */
    federation_name?: string | null;
    /**
     * License Expires At
     */
    license_expires_at?: string | null;
    /**
     * Emergency Contact Name
     */
    emergency_contact_name?: string | null;
    /**
     * Emergency Contact Phone
     */
    emergency_contact_phone?: string | null;
    /**
     * Emergency Contact Relationship
     */
    emergency_contact_relationship?: string | null;
    /**
     * School Name
     */
    school_name?: string | null;
    /**
     * School Level
     */
    school_level?: string | null;
    /**
     * Academic Workload Note
     */
    academic_workload_note?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * BloodTypeEnum
 *
 * Groupes ABO + Rh (données de santé sensibles — accès restreint).
 */
export type BloodTypeEnum = 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-' | 'UNKNOWN';

/**
 * ClubMemberSummary
 */
export type ClubMemberSummary = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
};

/**
 * CoachingLicenseLevelEnum
 *
 * Niveaux type UEFA / fédérations nationales (extensible).
 */
export type CoachingLicenseLevelEnum = 'GRASSROOTS' | 'C' | 'B' | 'A' | 'PRO' | 'NATIONAL' | 'OTHER';

/**
 * ConsentCreate
 */
export type ConsentCreate = {
    purpose: ConsentPurposeEnum;
    /**
     * Granted
     */
    granted: boolean;
    /**
     * Version
     */
    version?: string;
    /**
     * Organization Id
     */
    organization_id?: string | null;
};

/**
 * ConsentPurposeEnum
 */
export type ConsentPurposeEnum = 'ACCOUNT' | 'TRAINING_DATA' | 'HEALTH_SHARE' | 'MARKETING' | 'ANALYTICS' | 'PARENTAL';

/**
 * ConsentResponse
 */
export type ConsentResponse = {
    /**
     * Id
     */
    id: string;
    purpose: ConsentPurposeEnum;
    /**
     * Granted
     */
    granted: boolean;
    /**
     * Version
     */
    version: string;
    /**
     * Organization Id
     */
    organization_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CreateMemberRequest
 *
 * Créer un membre ou ajouter un rôle à un membre existant.
 * - Nouvel email → crée User + membership + profil
 * - Email déjà dans le club avec un autre rôle → ajoute le nouveau rôle + profil
 * - Même rôle déjà présent → erreur 400
 */
export type CreateMemberRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Rôle à assigner (un user peut en avoir plusieurs)
     */
    role: RoleEnum;
};

/**
 * DataExportResponse
 *
 * Export portabilite (RGPD art. 15/20 / CCPA).
 */
export type DataExportResponse = {
    /**
     * User
     */
    user: {
        [key: string]: unknown;
    };
    /**
     * Memberships
     */
    memberships: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Profiles
     */
    profiles: {
        [key: string]: unknown;
    };
    /**
     * Consents
     */
    consents: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Wellness Checkins
     */
    wellness_checkins: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Session Rpe Logs
     */
    session_rpe_logs: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Daily Training Loads
     */
    daily_training_loads: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Exported At
     */
    exported_at: string;
};

/**
 * DeleteAccountResponse
 */
export type DeleteAccountResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Deleted At
     */
    deleted_at: string;
    /**
     * Purge After Days
     */
    purge_after_days: number;
};

/**
 * DominantSideEnum
 */
export type DominantSideEnum = 'LEFT' | 'RIGHT' | 'BOTH';

/**
 * ErrorDetail
 *
 * Corps d'erreur standard FastAPI.
 */
export type ErrorDetail = {
    /**
     * Detail
     *
     * Message d'erreur ou liste d'erreurs de validation
     */
    detail: string | Array<unknown>;
};

/**
 * ForgotPasswordRequest
 */
export type ForgotPasswordRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * ForgotPasswordResponse
 */
export type ForgotPasswordResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Reset Token
     */
    reset_token?: string | null;
};

/**
 * GenderEnum
 *
 * Aligné pratiques IOC / ODF (PERSON_GENDER).
 */
export type GenderEnum = 'MALE' | 'FEMALE' | 'OTHER' | 'UNDISCLOSED';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthProProfileResponse
 */
export type HealthProProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Secondary Language Code
     */
    secondary_language_code?: string | null;
    specialty?: HealthSpecialtyEnum | null;
    /**
     * Sub Specialty
     */
    sub_specialty?: string | null;
    /**
     * License Number
     */
    license_number?: string | null;
    /**
     * License Country Code
     */
    license_country_code?: string | null;
    /**
     * License Expires At
     */
    license_expires_at?: string | null;
    /**
     * Professional Body
     */
    professional_body?: string | null;
    /**
     * Organization Name
     */
    organization_name?: string | null;
    /**
     * Practice Country Code
     */
    practice_country_code?: string | null;
    /**
     * Practice City
     */
    practice_city?: string | null;
    /**
     * Years Of Experience
     */
    years_of_experience?: number | null;
    /**
     * Liability Insurance Provider
     */
    liability_insurance_provider?: string | null;
    /**
     * Liability Insurance Number
     */
    liability_insurance_number?: string | null;
    /**
     * Liability Insurance Expires At
     */
    liability_insurance_expires_at?: string | null;
    /**
     * Background Check Declared
     */
    background_check_declared: boolean;
    /**
     * Background Check Date
     */
    background_check_date?: string | null;
    /**
     * Background Check Expires
     */
    background_check_expires?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Website Url
     */
    website_url?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HealthProProfileUpdate
 */
export type HealthProProfileUpdate = {
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Secondary Language Code
     */
    secondary_language_code?: string | null;
    specialty?: HealthSpecialtyEnum | null;
    /**
     * Sub Specialty
     */
    sub_specialty?: string | null;
    /**
     * License Number
     */
    license_number?: string | null;
    /**
     * License Country Code
     */
    license_country_code?: string | null;
    /**
     * License Expires At
     */
    license_expires_at?: string | null;
    /**
     * Professional Body
     */
    professional_body?: string | null;
    /**
     * Organization Name
     */
    organization_name?: string | null;
    /**
     * Practice Country Code
     */
    practice_country_code?: string | null;
    /**
     * Practice City
     */
    practice_city?: string | null;
    /**
     * Years Of Experience
     */
    years_of_experience?: number | null;
    /**
     * Liability Insurance Provider
     */
    liability_insurance_provider?: string | null;
    /**
     * Liability Insurance Number
     */
    liability_insurance_number?: string | null;
    /**
     * Liability Insurance Expires At
     */
    liability_insurance_expires_at?: string | null;
    /**
     * Background Check Declared
     */
    background_check_declared?: boolean | null;
    /**
     * Background Check Date
     */
    background_check_date?: string | null;
    /**
     * Background Check Expires
     */
    background_check_expires?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Website Url
     */
    website_url?: string | null;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Project
     */
    project: string;
};

/**
 * HealthSpecialtyEnum
 */
export type HealthSpecialtyEnum = 'PHYSIOTHERAPIST' | 'SPORTS_PHYSICIAN' | 'GENERAL_PRACTITIONER' | 'ORTHOPEDIST' | 'NUTRITIONIST' | 'PSYCHOLOGIST' | 'OSTEOPATH' | 'NURSE' | 'OTHER';

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    user: UserBaseResponse;
    /**
     * Must Change Password
     */
    must_change_password?: boolean;
};

/**
 * MemberListResponse
 */
export type MemberListResponse = {
    /**
     * Items
     */
    items: Array<MemberResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * MemberResponse
 *
 * Une ligne membership = un rôle.
 */
export type MemberResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    role: RoleEnum;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    user: MemberUserSummary;
    /**
     * Generated Password
     *
     * Mot de passe généré uniquement à la création d'un nouvel utilisateur
     */
    generated_password?: string | null;
};

/**
 * MemberUserSummary
 */
export type MemberUserSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * OrganizationDetailResponse
 */
export type OrganizationDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Sport
     */
    sport: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Members
     */
    members?: Array<ClubMemberSummary>;
};

/**
 * OrganizationResponse
 */
export type OrganizationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Sport
     */
    sport: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * OrganizationSummary
 */
export type OrganizationSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Sport
     */
    sport: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ParentAthleteLinkCreate
 */
export type ParentAthleteLinkCreate = {
    /**
     * Parent User Id
     */
    parent_user_id: string;
    /**
     * Athlete User Id
     */
    athlete_user_id: string;
    relationship?: ParentRelationshipEnum;
    /**
     * Is Primary Contact
     */
    is_primary_contact?: boolean;
    /**
     * Is Legal Guardian
     */
    is_legal_guardian?: boolean;
};

/**
 * ParentAthleteLinkResponse
 */
export type ParentAthleteLinkResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Parent User Id
     */
    parent_user_id: string;
    /**
     * Athlete User Id
     */
    athlete_user_id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    relationship: ParentRelationshipEnum;
    /**
     * Is Primary Contact
     */
    is_primary_contact: boolean;
    /**
     * Is Legal Guardian
     */
    is_legal_guardian: boolean;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ParentProfileResponse
 */
export type ParentProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    /**
     * Address Line1
     */
    address_line1?: string | null;
    /**
     * Address Line2
     */
    address_line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State Province
     */
    state_province?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country Code
     */
    country_code?: string | null;
    /**
     * Secondary Phone
     */
    secondary_phone?: string | null;
    /**
     * Emergency Phone
     */
    emergency_phone?: string | null;
    /**
     * Work Phone
     */
    work_phone?: string | null;
    /**
     * Preferred Contact Method
     */
    preferred_contact_method?: string | null;
    /**
     * Occupation
     */
    occupation?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ParentProfileUpdate
 */
export type ParentProfileUpdate = {
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    /**
     * Address Line1
     */
    address_line1?: string | null;
    /**
     * Address Line2
     */
    address_line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State Province
     */
    state_province?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country Code
     */
    country_code?: string | null;
    /**
     * Secondary Phone
     */
    secondary_phone?: string | null;
    /**
     * Emergency Phone
     */
    emergency_phone?: string | null;
    /**
     * Work Phone
     */
    work_phone?: string | null;
    /**
     * Preferred Contact Method
     */
    preferred_contact_method?: string | null;
    /**
     * Occupation
     */
    occupation?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * ParentRelationshipEnum
 */
export type ParentRelationshipEnum = 'FATHER' | 'MOTHER' | 'GUARDIAN' | 'STEP_PARENT' | 'OTHER';

/**
 * PermissionsExplanationResponse
 *
 * Roles + permissions resolues (UNION multi-roles) pour l'org active.
 */
export type PermissionsExplanationResponse = {
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Resolution
     */
    resolution?: string;
    /**
     * Permissions
     */
    permissions: Array<string>;
    /**
     * Sensitive Granted
     */
    sensitive_granted?: Array<string>;
    /**
     * By Role
     */
    by_role?: {
        [key: string]: Array<string>;
    };
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * RoleEnum
 *
 * Rôles alignés sur le cahier des charges Aikflow (section 3 + matrice §9).
 */
export type RoleEnum = 'SUPER_ADMIN' | 'CLUB_ADMIN' | 'COACH' | 'ASSISTANT_COACH' | 'STAFF' | 'ATHLETE' | 'PARENT' | 'HEALTH_PRO' | 'MARKETPLACE_PRO';

/**
 * SessionRpeCreate
 */
export type SessionRpeCreate = {
    /**
     * Duration Minutes
     *
     * Duree de la seance en minutes (1-600)
     */
    duration_minutes: number;
    /**
     * Rpe Score
     *
     * Intensite percue RPE (1-10)
     */
    rpe_score: number;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Session Date
     *
     * Defaut: aujourd'hui (UTC). Utile pour tests / rattrapage.
     */
    session_date?: string | null;
};

/**
 * SessionRpeDaySummary
 *
 * Resume d'une journee dans l'historique.
 */
export type SessionRpeDaySummary = {
    /**
     * Session Date
     */
    session_date: string;
    /**
     * Sessions Count
     */
    sessions_count: number;
    /**
     * Total Duration Minutes
     */
    total_duration_minutes: number;
    /**
     * Daily Load
     */
    daily_load: number;
    /**
     * Logs
     */
    logs: Array<SessionRpeResponse>;
};

/**
 * SessionRpeHistoryResponse
 */
export type SessionRpeHistoryResponse = {
    /**
     * Days
     */
    days: Array<SessionRpeDaySummary>;
    /**
     * Total Days
     */
    total_days: number;
};

/**
 * SessionRpeResponse
 *
 * Une seance individuelle.
 */
export type SessionRpeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Session Date
     */
    session_date: string;
    /**
     * Duration Minutes
     */
    duration_minutes: number;
    /**
     * Rpe Score
     */
    rpe_score: number;
    /**
     * Session Load
     */
    session_load: number;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Submitted At
     */
    submitted_at: string;
};

/**
 * SessionRpeScaleCatalog
 *
 * Catalogue RPE pour le front (boutons 1-10 + bandes).
 */
export type SessionRpeScaleCatalog = {
    /**
     * Scale
     */
    scale: {
        [key: string]: string;
    };
    /**
     * Bands
     */
    bands: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * SessionRpeTodayStatus
 *
 * Vue du jour : toutes les seances + Charge du Jour (somme).
 */
export type SessionRpeTodayStatus = {
    /**
     * Session Date
     */
    session_date: string;
    /**
     * Submitted
     */
    submitted: boolean;
    /**
     * Sessions Count
     */
    sessions_count: number;
    /**
     * Total Duration Minutes
     */
    total_duration_minutes: number;
    /**
     * Daily Load
     */
    daily_load: number;
    /**
     * Logs
     */
    logs: Array<SessionRpeResponse>;
};

/**
 * StaffProfileResponse
 */
export type StaffProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Secondary Language Code
     */
    secondary_language_code?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    gender?: GenderEnum | null;
    /**
     * Job Title
     */
    job_title?: string | null;
    /**
     * Years Of Experience
     */
    years_of_experience?: number | null;
    /**
     * Qualifications
     */
    qualifications?: string | null;
    coaching_license_level?: CoachingLicenseLevelEnum | null;
    /**
     * Coaching License Number
     */
    coaching_license_number?: string | null;
    /**
     * Coaching License Federation
     */
    coaching_license_federation?: string | null;
    /**
     * Coaching License Expires At
     */
    coaching_license_expires_at?: string | null;
    /**
     * Background Check Declared
     */
    background_check_declared: boolean;
    /**
     * Background Check Date
     */
    background_check_date?: string | null;
    /**
     * Background Check Expires
     */
    background_check_expires?: string | null;
    /**
     * Background Check Reference
     */
    background_check_reference?: string | null;
    /**
     * Safeguarding Training Completed
     */
    safeguarding_training_completed: boolean;
    /**
     * Safeguarding Training Date
     */
    safeguarding_training_date?: string | null;
    /**
     * Safeguarding Training Expires
     */
    safeguarding_training_expires?: string | null;
    /**
     * Safeguarding Certificate Ref
     */
    safeguarding_certificate_ref?: string | null;
    /**
     * Is Safeguarding Compliant
     */
    is_safeguarding_compliant: boolean;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * StaffProfileUpdate
 */
export type StaffProfileUpdate = {
    /**
     * Nationality Code
     */
    nationality_code?: string | null;
    /**
     * Preferred Language Code
     */
    preferred_language_code?: string | null;
    /**
     * Secondary Language Code
     */
    secondary_language_code?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    gender?: GenderEnum | null;
    /**
     * Job Title
     */
    job_title?: string | null;
    /**
     * Years Of Experience
     */
    years_of_experience?: number | null;
    /**
     * Qualifications
     */
    qualifications?: string | null;
    coaching_license_level?: CoachingLicenseLevelEnum | null;
    /**
     * Coaching License Number
     */
    coaching_license_number?: string | null;
    /**
     * Coaching License Federation
     */
    coaching_license_federation?: string | null;
    /**
     * Coaching License Expires At
     */
    coaching_license_expires_at?: string | null;
    /**
     * Background Check Declared
     */
    background_check_declared?: boolean | null;
    /**
     * Background Check Date
     */
    background_check_date?: string | null;
    /**
     * Background Check Expires
     */
    background_check_expires?: string | null;
    /**
     * Background Check Reference
     */
    background_check_reference?: string | null;
    /**
     * Safeguarding Training Completed
     */
    safeguarding_training_completed?: boolean | null;
    /**
     * Safeguarding Training Date
     */
    safeguarding_training_date?: string | null;
    /**
     * Safeguarding Training Expires
     */
    safeguarding_training_expires?: string | null;
    /**
     * Safeguarding Certificate Ref
     */
    safeguarding_certificate_ref?: string | null;
    /**
     * Photo Url
     */
    photo_url?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * TeamCreate
 */
export type TeamCreate = {
    /**
     * Name
     */
    name: string;
    age_category: AgeCategoryEnum;
    gender?: TeamGenderEnum;
    /**
     * Season
     */
    season?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Max Roster Size
     */
    max_roster_size?: number | null;
};

/**
 * TeamDetailResponse
 */
export type TeamDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    age_category: AgeCategoryEnum;
    gender: TeamGenderEnum;
    /**
     * Season
     */
    season?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Max Roster Size
     */
    max_roster_size?: number | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Members Count
     */
    members_count?: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Members
     */
    members?: Array<TeamMemberResponse>;
};

/**
 * TeamGenderEnum
 */
export type TeamGenderEnum = 'MALE' | 'FEMALE' | 'MIXED';

/**
 * TeamListResponse
 */
export type TeamListResponse = {
    /**
     * Items
     */
    items: Array<TeamResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * TeamMemberAdd
 */
export type TeamMemberAdd = {
    /**
     * User Id
     */
    user_id: string;
    role_in_team?: TeamMemberRoleEnum;
    /**
     * Jersey Number
     */
    jersey_number?: number | null;
    /**
     * Is Captain
     */
    is_captain?: boolean;
};

/**
 * TeamMemberResponse
 */
export type TeamMemberResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Team Id
     */
    team_id: string;
    /**
     * User Id
     */
    user_id: string;
    role_in_team: TeamMemberRoleEnum;
    /**
     * Jersey Number
     */
    jersey_number?: number | null;
    /**
     * Is Captain
     */
    is_captain: boolean;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    user?: TeamMemberUserSummary | null;
};

/**
 * TeamMemberRoleEnum
 *
 * Rôle dans l'équipe (distinct du RoleEnum org).
 */
export type TeamMemberRoleEnum = 'ATHLETE' | 'COACH' | 'ASSISTANT_COACH' | 'STAFF';

/**
 * TeamMemberUpdate
 */
export type TeamMemberUpdate = {
    role_in_team?: TeamMemberRoleEnum | null;
    /**
     * Jersey Number
     */
    jersey_number?: number | null;
    /**
     * Is Captain
     */
    is_captain?: boolean | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * TeamMemberUserSummary
 */
export type TeamMemberUserSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * TeamResponse
 */
export type TeamResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    age_category: AgeCategoryEnum;
    gender: TeamGenderEnum;
    /**
     * Season
     */
    season?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Max Roster Size
     */
    max_roster_size?: number | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Members Count
     */
    members_count?: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TeamUpdate
 */
export type TeamUpdate = {
    /**
     * Name
     */
    name?: string | null;
    age_category?: AgeCategoryEnum | null;
    gender?: TeamGenderEnum | null;
    /**
     * Season
     */
    season?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Max Roster Size
     */
    max_roster_size?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * TeamWellnessRadarItem
 */
export type TeamWellnessRadarItem = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Submitted
     */
    submitted: boolean;
    /**
     * Wellness Score
     */
    wellness_score?: number | null;
    /**
     * Drop Alert
     */
    drop_alert?: boolean;
    /**
     * Sleep Quality
     */
    sleep_quality?: number | null;
    /**
     * Energy Level
     */
    energy_level?: number | null;
    /**
     * Muscle Soreness
     */
    muscle_soreness?: number | null;
    /**
     * Stress Level
     */
    stress_level?: number | null;
    /**
     * Motivation
     */
    motivation?: number | null;
};

/**
 * TeamWellnessRadarResponse
 */
export type TeamWellnessRadarResponse = {
    /**
     * Team Id
     */
    team_id: string;
    /**
     * Checkin Date
     */
    checkin_date: string;
    /**
     * Submitted Count
     */
    submitted_count: number;
    /**
     * Total Athletes
     */
    total_athletes: number;
    /**
     * Average Score
     */
    average_score?: number | null;
    /**
     * Drop Alerts Count
     */
    drop_alerts_count: number;
    /**
     * Items
     */
    items: Array<TeamWellnessRadarItem>;
};

/**
 * UpdateMemberRequest
 *
 * Modifier le statut d'un membership (une ligne = un rôle).
 */
export type UpdateMemberRequest = {
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * UserBaseResponse
 */
export type UserBaseResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Memberships
     */
    memberships?: Array<UserMembershipResponse>;
};

/**
 * UserMembershipResponse
 */
export type UserMembershipResponse = {
    /**
     * Role
     */
    role: string;
    organization: OrganizationSummary;
};

/**
 * UserWithRolesListResponse
 */
export type UserWithRolesListResponse = {
    /**
     * Items
     */
    items: Array<UserWithRolesResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * UserWithRolesResponse
 *
 * Vue regroupée : un utilisateur + tous ses rôles dans le club.
 */
export type UserWithRolesResponse = {
    user: MemberUserSummary;
    /**
     * Roles
     */
    roles: Array<RoleEnum>;
    /**
     * Memberships
     */
    memberships: Array<MemberResponse>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WellnessCheckinCreate
 */
export type WellnessCheckinCreate = {
    /**
     * Sleep Quality
     *
     * Qualite du sommeil
     */
    sleep_quality: number;
    /**
     * Energy Level
     *
     * Niveau d'energie / fatigue
     */
    energy_level: number;
    /**
     * Muscle Soreness
     *
     * Courbatures & douleurs
     */
    muscle_soreness: number;
    /**
     * Stress Level
     *
     * Stress & anxiete
     */
    stress_level: number;
    /**
     * Motivation
     *
     * Motivation / envie
     */
    motivation: number;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Checkin Date
     *
     * Defaut: aujourd'hui (UTC date). Utile tests / rattrapage coach.
     */
    checkin_date?: string | null;
};

/**
 * WellnessCheckinResponse
 */
export type WellnessCheckinResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Checkin Date
     */
    checkin_date: string;
    /**
     * Sleep Quality
     */
    sleep_quality: number;
    /**
     * Energy Level
     */
    energy_level: number;
    /**
     * Muscle Soreness
     */
    muscle_soreness: number;
    /**
     * Stress Level
     */
    stress_level: number;
    /**
     * Motivation
     */
    motivation: number;
    /**
     * Wellness Score
     */
    wellness_score: number;
    /**
     * Drop Alert
     */
    drop_alert: boolean;
    /**
     * Previous Score
     */
    previous_score?: number | null;
    /**
     * Drop Percent
     */
    drop_percent?: number | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Submitted At
     */
    submitted_at: string;
};

/**
 * WellnessHistoryResponse
 */
export type WellnessHistoryResponse = {
    /**
     * Items
     */
    items: Array<WellnessCheckinResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * WellnessQuestionCatalog
 *
 * Catalogue des questions pour le front (labels 1-5).
 */
export type WellnessQuestionCatalog = {
    /**
     * Questions
     */
    questions: {
        [key: string]: unknown;
    };
};

/**
 * WellnessTodayStatus
 */
export type WellnessTodayStatus = {
    /**
     * Checkin Date
     */
    checkin_date: string;
    /**
     * Submitted
     */
    submitted: boolean;
    checkin?: WellnessCheckinResponse | null;
};

/**
 * Organisation active. Obligatoire si l'utilisateur a plusieurs memberships.
 */
export type XOrganizationId = string;

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthGetMeErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type AuthGetMeError = AuthGetMeErrors[keyof AuthGetMeErrors];

export type AuthGetMeResponses = {
    /**
     * Successful Response
     */
    200: UserBaseResponse;
};

export type AuthGetMeResponse = AuthGetMeResponses[keyof AuthGetMeResponses];

export type AuthForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type AuthForgotPasswordErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type AuthForgotPasswordError = AuthForgotPasswordErrors[keyof AuthForgotPasswordErrors];

export type AuthForgotPasswordResponses = {
    /**
     * Successful Response
     */
    200: ForgotPasswordResponse;
};

export type AuthForgotPasswordResponse = AuthForgotPasswordResponses[keyof AuthForgotPasswordResponses];

export type AuthResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type AuthResetPasswordErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type AuthResetPasswordError = AuthResetPasswordErrors[keyof AuthResetPasswordErrors];

export type AuthResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type AuthResetPasswordResponse = AuthResetPasswordResponses[keyof AuthResetPasswordResponses];

export type AdminorgsListClubsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/organizations';
};

export type AdminorgsListClubsResponses = {
    /**
     * Response Adminorgs List Clubs
     *
     * Successful Response
     */
    200: Array<OrganizationResponse>;
};

export type AdminorgsListClubsResponse = AdminorgsListClubsResponses[keyof AdminorgsListClubsResponses];

export type AdminorgsCreateClubByAdminData = {
    body: AdminCreateClubRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/organizations';
};

export type AdminorgsCreateClubByAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminorgsCreateClubByAdminError = AdminorgsCreateClubByAdminErrors[keyof AdminorgsCreateClubByAdminErrors];

export type AdminorgsCreateClubByAdminResponses = {
    /**
     * Successful Response
     */
    201: AdminCreateClubResponse;
};

export type AdminorgsCreateClubByAdminResponse = AdminorgsCreateClubByAdminResponses[keyof AdminorgsCreateClubByAdminResponses];

export type AdminorgsGetClubDetailData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/admin/organizations/{org_id}';
};

export type AdminorgsGetClubDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminorgsGetClubDetailError = AdminorgsGetClubDetailErrors[keyof AdminorgsGetClubDetailErrors];

export type AdminorgsGetClubDetailResponses = {
    /**
     * Successful Response
     */
    200: OrganizationDetailResponse;
};

export type AdminorgsGetClubDetailResponse = AdminorgsGetClubDetailResponses[keyof AdminorgsGetClubDetailResponses];

export type AdminorgsUpdateClubData = {
    body: AdminUpdateClubRequest;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/admin/organizations/{org_id}';
};

export type AdminorgsUpdateClubErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminorgsUpdateClubError = AdminorgsUpdateClubErrors[keyof AdminorgsUpdateClubErrors];

export type AdminorgsUpdateClubResponses = {
    /**
     * Successful Response
     */
    200: OrganizationResponse;
};

export type AdminorgsUpdateClubResponse = AdminorgsUpdateClubResponses[keyof AdminorgsUpdateClubResponses];

export type MembersListMembersData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Role
         */
        role?: RoleEnum | null;
        /**
         * Active Only
         */
        active_only?: boolean;
    };
    url: '/api/v1/organizations/members';
};

export type MembersListMembersErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersListMembersError = MembersListMembersErrors[keyof MembersListMembersErrors];

export type MembersListMembersResponses = {
    /**
     * Successful Response
     */
    200: MemberListResponse;
};

export type MembersListMembersResponse = MembersListMembersResponses[keyof MembersListMembersResponses];

export type MembersCreateMemberData = {
    body: CreateMemberRequest;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/members';
};

export type MembersCreateMemberErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersCreateMemberError = MembersCreateMemberErrors[keyof MembersCreateMemberErrors];

export type MembersCreateMemberResponses = {
    /**
     * Successful Response
     */
    201: MemberResponse;
};

export type MembersCreateMemberResponse = MembersCreateMemberResponses[keyof MembersCreateMemberResponses];

export type MembersAddRoleData = {
    body: AddRoleRequest;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/members/roles';
};

export type MembersAddRoleErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersAddRoleError = MembersAddRoleErrors[keyof MembersAddRoleErrors];

export type MembersAddRoleResponses = {
    /**
     * Successful Response
     */
    201: MemberResponse;
};

export type MembersAddRoleResponse = MembersAddRoleResponses[keyof MembersAddRoleResponses];

export type MembersListMembersByUserData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Active Only
         */
        active_only?: boolean;
    };
    url: '/api/v1/organizations/members/by-user';
};

export type MembersListMembersByUserErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersListMembersByUserError = MembersListMembersByUserErrors[keyof MembersListMembersByUserErrors];

export type MembersListMembersByUserResponses = {
    /**
     * Successful Response
     */
    200: UserWithRolesListResponse;
};

export type MembersListMembersByUserResponse = MembersListMembersByUserResponses[keyof MembersListMembersByUserResponses];

export type MembersMyPermissionsData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/members/me/permissions';
};

export type MembersMyPermissionsErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersMyPermissionsError = MembersMyPermissionsErrors[keyof MembersMyPermissionsErrors];

export type MembersMyPermissionsResponses = {
    /**
     * Successful Response
     */
    200: PermissionsExplanationResponse;
};

export type MembersMyPermissionsResponse = MembersMyPermissionsResponses[keyof MembersMyPermissionsResponses];

export type MembersRemoveMemberData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Membership Id
         */
        membership_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/members/{membership_id}';
};

export type MembersRemoveMemberErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersRemoveMemberError = MembersRemoveMemberErrors[keyof MembersRemoveMemberErrors];

export type MembersRemoveMemberResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MembersRemoveMemberResponse = MembersRemoveMemberResponses[keyof MembersRemoveMemberResponses];

export type MembersGetMemberData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Membership Id
         */
        membership_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/members/{membership_id}';
};

export type MembersGetMemberErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersGetMemberError = MembersGetMemberErrors[keyof MembersGetMemberErrors];

export type MembersGetMemberResponses = {
    /**
     * Successful Response
     */
    200: MemberResponse;
};

export type MembersGetMemberResponse = MembersGetMemberResponses[keyof MembersGetMemberResponses];

export type MembersUpdateMemberData = {
    body: UpdateMemberRequest;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Membership Id
         */
        membership_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/members/{membership_id}';
};

export type MembersUpdateMemberErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type MembersUpdateMemberError = MembersUpdateMemberErrors[keyof MembersUpdateMemberErrors];

export type MembersUpdateMemberResponses = {
    /**
     * Successful Response
     */
    200: MemberResponse;
};

export type MembersUpdateMemberResponse = MembersUpdateMemberResponses[keyof MembersUpdateMemberResponses];

export type ProfilesMeAthleteProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/athlete';
};

export type ProfilesMeAthleteProfileResponses = {
    /**
     * Successful Response
     */
    200: AthleteProfileResponse;
};

export type ProfilesMeAthleteProfileResponse = ProfilesMeAthleteProfileResponses[keyof ProfilesMeAthleteProfileResponses];

export type ProfilesMeUpdateAthleteData = {
    body: AthleteProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/athlete';
};

export type ProfilesMeUpdateAthleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesMeUpdateAthleteError = ProfilesMeUpdateAthleteErrors[keyof ProfilesMeUpdateAthleteErrors];

export type ProfilesMeUpdateAthleteResponses = {
    /**
     * Successful Response
     */
    200: AthleteProfileResponse;
};

export type ProfilesMeUpdateAthleteResponse = ProfilesMeUpdateAthleteResponses[keyof ProfilesMeUpdateAthleteResponses];

export type ProfilesMeParentProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/parent';
};

export type ProfilesMeParentProfileResponses = {
    /**
     * Successful Response
     */
    200: ParentProfileResponse;
};

export type ProfilesMeParentProfileResponse = ProfilesMeParentProfileResponses[keyof ProfilesMeParentProfileResponses];

export type ProfilesMeUpdateParentData = {
    body: ParentProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/parent';
};

export type ProfilesMeUpdateParentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesMeUpdateParentError = ProfilesMeUpdateParentErrors[keyof ProfilesMeUpdateParentErrors];

export type ProfilesMeUpdateParentResponses = {
    /**
     * Successful Response
     */
    200: ParentProfileResponse;
};

export type ProfilesMeUpdateParentResponse = ProfilesMeUpdateParentResponses[keyof ProfilesMeUpdateParentResponses];

export type ProfilesMeStaffProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/staff';
};

export type ProfilesMeStaffProfileResponses = {
    /**
     * Successful Response
     */
    200: StaffProfileResponse;
};

export type ProfilesMeStaffProfileResponse = ProfilesMeStaffProfileResponses[keyof ProfilesMeStaffProfileResponses];

export type ProfilesMeUpdateStaffData = {
    body: StaffProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/staff';
};

export type ProfilesMeUpdateStaffErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesMeUpdateStaffError = ProfilesMeUpdateStaffErrors[keyof ProfilesMeUpdateStaffErrors];

export type ProfilesMeUpdateStaffResponses = {
    /**
     * Successful Response
     */
    200: StaffProfileResponse;
};

export type ProfilesMeUpdateStaffResponse = ProfilesMeUpdateStaffResponses[keyof ProfilesMeUpdateStaffResponses];

export type ProfilesMeHealthProProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/health-pro';
};

export type ProfilesMeHealthProProfileResponses = {
    /**
     * Successful Response
     */
    200: HealthProProfileResponse;
};

export type ProfilesMeHealthProProfileResponse = ProfilesMeHealthProProfileResponses[keyof ProfilesMeHealthProProfileResponses];

export type ProfilesMeUpdateHealthProData = {
    body: HealthProProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/me/health-pro';
};

export type ProfilesMeUpdateHealthProErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesMeUpdateHealthProError = ProfilesMeUpdateHealthProErrors[keyof ProfilesMeUpdateHealthProErrors];

export type ProfilesMeUpdateHealthProResponses = {
    /**
     * Successful Response
     */
    200: HealthProProfileResponse;
};

export type ProfilesMeUpdateHealthProResponse = ProfilesMeUpdateHealthProResponses[keyof ProfilesMeUpdateHealthProResponses];

export type ProfilesAdminGetAthleteData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/athlete';
};

export type ProfilesAdminGetAthleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminGetAthleteError = ProfilesAdminGetAthleteErrors[keyof ProfilesAdminGetAthleteErrors];

export type ProfilesAdminGetAthleteResponses = {
    /**
     * Successful Response
     */
    200: AthleteProfileResponse;
};

export type ProfilesAdminGetAthleteResponse = ProfilesAdminGetAthleteResponses[keyof ProfilesAdminGetAthleteResponses];

export type ProfilesAdminUpdateAthleteData = {
    body: AthleteProfileUpdate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/athlete';
};

export type ProfilesAdminUpdateAthleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminUpdateAthleteError = ProfilesAdminUpdateAthleteErrors[keyof ProfilesAdminUpdateAthleteErrors];

export type ProfilesAdminUpdateAthleteResponses = {
    /**
     * Successful Response
     */
    200: AthleteProfileResponse;
};

export type ProfilesAdminUpdateAthleteResponse = ProfilesAdminUpdateAthleteResponses[keyof ProfilesAdminUpdateAthleteResponses];

export type ProfilesAdminGetParentData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/parent';
};

export type ProfilesAdminGetParentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminGetParentError = ProfilesAdminGetParentErrors[keyof ProfilesAdminGetParentErrors];

export type ProfilesAdminGetParentResponses = {
    /**
     * Successful Response
     */
    200: ParentProfileResponse;
};

export type ProfilesAdminGetParentResponse = ProfilesAdminGetParentResponses[keyof ProfilesAdminGetParentResponses];

export type ProfilesAdminUpdateParentData = {
    body: ParentProfileUpdate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/parent';
};

export type ProfilesAdminUpdateParentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminUpdateParentError = ProfilesAdminUpdateParentErrors[keyof ProfilesAdminUpdateParentErrors];

export type ProfilesAdminUpdateParentResponses = {
    /**
     * Successful Response
     */
    200: ParentProfileResponse;
};

export type ProfilesAdminUpdateParentResponse = ProfilesAdminUpdateParentResponses[keyof ProfilesAdminUpdateParentResponses];

export type ProfilesAdminGetStaffData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/staff';
};

export type ProfilesAdminGetStaffErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminGetStaffError = ProfilesAdminGetStaffErrors[keyof ProfilesAdminGetStaffErrors];

export type ProfilesAdminGetStaffResponses = {
    /**
     * Successful Response
     */
    200: StaffProfileResponse;
};

export type ProfilesAdminGetStaffResponse = ProfilesAdminGetStaffResponses[keyof ProfilesAdminGetStaffResponses];

export type ProfilesAdminUpdateStaffData = {
    body: StaffProfileUpdate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/staff';
};

export type ProfilesAdminUpdateStaffErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminUpdateStaffError = ProfilesAdminUpdateStaffErrors[keyof ProfilesAdminUpdateStaffErrors];

export type ProfilesAdminUpdateStaffResponses = {
    /**
     * Successful Response
     */
    200: StaffProfileResponse;
};

export type ProfilesAdminUpdateStaffResponse = ProfilesAdminUpdateStaffResponses[keyof ProfilesAdminUpdateStaffResponses];

export type ProfilesAdminGetHealthProData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/health-pro';
};

export type ProfilesAdminGetHealthProErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminGetHealthProError = ProfilesAdminGetHealthProErrors[keyof ProfilesAdminGetHealthProErrors];

export type ProfilesAdminGetHealthProResponses = {
    /**
     * Successful Response
     */
    200: HealthProProfileResponse;
};

export type ProfilesAdminGetHealthProResponse = ProfilesAdminGetHealthProResponses[keyof ProfilesAdminGetHealthProResponses];

export type ProfilesAdminUpdateHealthProData = {
    body: HealthProProfileUpdate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/users/{user_id}/health-pro';
};

export type ProfilesAdminUpdateHealthProErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesAdminUpdateHealthProError = ProfilesAdminUpdateHealthProErrors[keyof ProfilesAdminUpdateHealthProErrors];

export type ProfilesAdminUpdateHealthProResponses = {
    /**
     * Successful Response
     */
    200: HealthProProfileResponse;
};

export type ProfilesAdminUpdateHealthProResponse = ProfilesAdminUpdateHealthProResponses[keyof ProfilesAdminUpdateHealthProResponses];

export type ProfilesListLinksData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/profiles/parent-athlete-links';
};

export type ProfilesListLinksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesListLinksError = ProfilesListLinksErrors[keyof ProfilesListLinksErrors];

export type ProfilesListLinksResponses = {
    /**
     * Response Profiles List Links
     *
     * Successful Response
     */
    200: Array<ParentAthleteLinkResponse>;
};

export type ProfilesListLinksResponse = ProfilesListLinksResponses[keyof ProfilesListLinksResponses];

export type ProfilesCreateLinkData = {
    body: ParentAthleteLinkCreate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/profiles/parent-athlete-links';
};

export type ProfilesCreateLinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesCreateLinkError = ProfilesCreateLinkErrors[keyof ProfilesCreateLinkErrors];

export type ProfilesCreateLinkResponses = {
    /**
     * Successful Response
     */
    201: ParentAthleteLinkResponse;
};

export type ProfilesCreateLinkResponse = ProfilesCreateLinkResponses[keyof ProfilesCreateLinkResponses];

export type ProfilesDeleteLinkData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Link Id
         */
        link_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/parent-athlete-links/{link_id}';
};

export type ProfilesDeleteLinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfilesDeleteLinkError = ProfilesDeleteLinkErrors[keyof ProfilesDeleteLinkErrors];

export type ProfilesDeleteLinkResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ProfilesDeleteLinkResponse = ProfilesDeleteLinkResponses[keyof ProfilesDeleteLinkResponses];

export type TeamsListTeamsEndpointData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Active Only
         */
        active_only?: boolean;
    };
    url: '/api/v1/teams';
};

export type TeamsListTeamsEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsListTeamsEndpointError = TeamsListTeamsEndpointErrors[keyof TeamsListTeamsEndpointErrors];

export type TeamsListTeamsEndpointResponses = {
    /**
     * Successful Response
     */
    200: TeamListResponse;
};

export type TeamsListTeamsEndpointResponse = TeamsListTeamsEndpointResponses[keyof TeamsListTeamsEndpointResponses];

export type TeamsCreateTeamEndpointData = {
    body: TeamCreate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/teams';
};

export type TeamsCreateTeamEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsCreateTeamEndpointError = TeamsCreateTeamEndpointErrors[keyof TeamsCreateTeamEndpointErrors];

export type TeamsCreateTeamEndpointResponses = {
    /**
     * Successful Response
     */
    201: TeamResponse;
};

export type TeamsCreateTeamEndpointResponse = TeamsCreateTeamEndpointResponses[keyof TeamsCreateTeamEndpointResponses];

export type TeamsDeleteTeamEndpointData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Team Id
         */
        team_id: string;
    };
    query?: never;
    url: '/api/v1/teams/{team_id}';
};

export type TeamsDeleteTeamEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsDeleteTeamEndpointError = TeamsDeleteTeamEndpointErrors[keyof TeamsDeleteTeamEndpointErrors];

export type TeamsDeleteTeamEndpointResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TeamsDeleteTeamEndpointResponse = TeamsDeleteTeamEndpointResponses[keyof TeamsDeleteTeamEndpointResponses];

export type TeamsGetTeamEndpointData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Team Id
         */
        team_id: string;
    };
    query?: never;
    url: '/api/v1/teams/{team_id}';
};

export type TeamsGetTeamEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsGetTeamEndpointError = TeamsGetTeamEndpointErrors[keyof TeamsGetTeamEndpointErrors];

export type TeamsGetTeamEndpointResponses = {
    /**
     * Successful Response
     */
    200: TeamDetailResponse;
};

export type TeamsGetTeamEndpointResponse = TeamsGetTeamEndpointResponses[keyof TeamsGetTeamEndpointResponses];

export type TeamsUpdateTeamEndpointData = {
    body: TeamUpdate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Team Id
         */
        team_id: string;
    };
    query?: never;
    url: '/api/v1/teams/{team_id}';
};

export type TeamsUpdateTeamEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsUpdateTeamEndpointError = TeamsUpdateTeamEndpointErrors[keyof TeamsUpdateTeamEndpointErrors];

export type TeamsUpdateTeamEndpointResponses = {
    /**
     * Successful Response
     */
    200: TeamResponse;
};

export type TeamsUpdateTeamEndpointResponse = TeamsUpdateTeamEndpointResponses[keyof TeamsUpdateTeamEndpointResponses];

export type TeamsAddMemberEndpointData = {
    body: TeamMemberAdd;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Team Id
         */
        team_id: string;
    };
    query?: never;
    url: '/api/v1/teams/{team_id}/members';
};

export type TeamsAddMemberEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsAddMemberEndpointError = TeamsAddMemberEndpointErrors[keyof TeamsAddMemberEndpointErrors];

export type TeamsAddMemberEndpointResponses = {
    /**
     * Successful Response
     */
    201: TeamMemberResponse;
};

export type TeamsAddMemberEndpointResponse = TeamsAddMemberEndpointResponses[keyof TeamsAddMemberEndpointResponses];

export type TeamsRemoveMemberEndpointData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Team Id
         */
        team_id: string;
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/teams/{team_id}/members/{member_id}';
};

export type TeamsRemoveMemberEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsRemoveMemberEndpointError = TeamsRemoveMemberEndpointErrors[keyof TeamsRemoveMemberEndpointErrors];

export type TeamsRemoveMemberEndpointResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TeamsRemoveMemberEndpointResponse = TeamsRemoveMemberEndpointResponses[keyof TeamsRemoveMemberEndpointResponses];

export type TeamsUpdateMemberEndpointData = {
    body: TeamMemberUpdate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Team Id
         */
        team_id: string;
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/teams/{team_id}/members/{member_id}';
};

export type TeamsUpdateMemberEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeamsUpdateMemberEndpointError = TeamsUpdateMemberEndpointErrors[keyof TeamsUpdateMemberEndpointErrors];

export type TeamsUpdateMemberEndpointResponses = {
    /**
     * Successful Response
     */
    200: TeamMemberResponse;
};

export type TeamsUpdateMemberEndpointResponse = TeamsUpdateMemberEndpointResponses[keyof TeamsUpdateMemberEndpointResponses];

export type PrivacyListConsentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/privacy/consents';
};

export type PrivacyListConsentsErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type PrivacyListConsentsError = PrivacyListConsentsErrors[keyof PrivacyListConsentsErrors];

export type PrivacyListConsentsResponses = {
    /**
     * Response Privacy List Consents
     *
     * Successful Response
     */
    200: Array<ConsentResponse>;
};

export type PrivacyListConsentsResponse = PrivacyListConsentsResponses[keyof PrivacyListConsentsResponses];

export type PrivacyCreateConsentData = {
    body: ConsentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/privacy/consents';
};

export type PrivacyCreateConsentErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type PrivacyCreateConsentError = PrivacyCreateConsentErrors[keyof PrivacyCreateConsentErrors];

export type PrivacyCreateConsentResponses = {
    /**
     * Successful Response
     */
    201: ConsentResponse;
};

export type PrivacyCreateConsentResponse = PrivacyCreateConsentResponses[keyof PrivacyCreateConsentResponses];

export type PrivacyExportMyDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/privacy/export';
};

export type PrivacyExportMyDataErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type PrivacyExportMyDataError = PrivacyExportMyDataErrors[keyof PrivacyExportMyDataErrors];

export type PrivacyExportMyDataResponses = {
    /**
     * Successful Response
     */
    200: DataExportResponse;
};

export type PrivacyExportMyDataResponse = PrivacyExportMyDataResponses[keyof PrivacyExportMyDataResponses];

export type PrivacyDeleteMyAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/privacy/me';
};

export type PrivacyDeleteMyAccountErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type PrivacyDeleteMyAccountError = PrivacyDeleteMyAccountErrors[keyof PrivacyDeleteMyAccountErrors];

export type PrivacyDeleteMyAccountResponses = {
    /**
     * Successful Response
     */
    200: DeleteAccountResponse;
};

export type PrivacyDeleteMyAccountResponse = PrivacyDeleteMyAccountResponses[keyof PrivacyDeleteMyAccountResponses];

export type WellnessGetQuestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wellness/questions';
};

export type WellnessGetQuestionsErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type WellnessGetQuestionsError = WellnessGetQuestionsErrors[keyof WellnessGetQuestionsErrors];

export type WellnessGetQuestionsResponses = {
    /**
     * Successful Response
     */
    200: WellnessQuestionCatalog;
};

export type WellnessGetQuestionsResponse = WellnessGetQuestionsResponses[keyof WellnessGetQuestionsResponses];

export type WellnessCreateCheckinData = {
    body: WellnessCheckinCreate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/wellness/checkins';
};

export type WellnessCreateCheckinErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type WellnessCreateCheckinError = WellnessCreateCheckinErrors[keyof WellnessCreateCheckinErrors];

export type WellnessCreateCheckinResponses = {
    /**
     * Successful Response
     */
    201: WellnessCheckinResponse;
};

export type WellnessCreateCheckinResponse = WellnessCreateCheckinResponses[keyof WellnessCreateCheckinResponses];

export type WellnessMeTodayData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * On Date
         */
        on_date?: string | null;
    };
    url: '/api/v1/wellness/me/today';
};

export type WellnessMeTodayErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type WellnessMeTodayError = WellnessMeTodayErrors[keyof WellnessMeTodayErrors];

export type WellnessMeTodayResponses = {
    /**
     * Successful Response
     */
    200: WellnessTodayStatus;
};

export type WellnessMeTodayResponse = WellnessMeTodayResponses[keyof WellnessMeTodayResponses];

export type WellnessMeHistoryData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/wellness/me/history';
};

export type WellnessMeHistoryErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type WellnessMeHistoryError = WellnessMeHistoryErrors[keyof WellnessMeHistoryErrors];

export type WellnessMeHistoryResponses = {
    /**
     * Successful Response
     */
    200: WellnessHistoryResponse;
};

export type WellnessMeHistoryResponse = WellnessMeHistoryResponses[keyof WellnessMeHistoryResponses];

export type WellnessAthleteTodayData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: {
        /**
         * On Date
         */
        on_date?: string | null;
    };
    url: '/api/v1/wellness/athletes/{user_id}/today';
};

export type WellnessAthleteTodayErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type WellnessAthleteTodayError = WellnessAthleteTodayErrors[keyof WellnessAthleteTodayErrors];

export type WellnessAthleteTodayResponses = {
    /**
     * Successful Response
     */
    200: WellnessCheckinResponse;
};

export type WellnessAthleteTodayResponse = WellnessAthleteTodayResponses[keyof WellnessAthleteTodayResponses];

export type WellnessRadarData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * Team Id
         */
        team_id: string;
    };
    query?: {
        /**
         * On Date
         */
        on_date?: string | null;
    };
    url: '/api/v1/wellness/teams/{team_id}/radar';
};

export type WellnessRadarErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type WellnessRadarError = WellnessRadarErrors[keyof WellnessRadarErrors];

export type WellnessRadarResponses = {
    /**
     * Successful Response
     */
    200: TeamWellnessRadarResponse;
};

export type WellnessRadarResponse = WellnessRadarResponses[keyof WellnessRadarResponses];

export type SessionrpeGetScaleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session-rpe/scale';
};

export type SessionrpeGetScaleErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type SessionrpeGetScaleError = SessionrpeGetScaleErrors[keyof SessionrpeGetScaleErrors];

export type SessionrpeGetScaleResponses = {
    /**
     * Successful Response
     */
    200: SessionRpeScaleCatalog;
};

export type SessionrpeGetScaleResponse = SessionrpeGetScaleResponses[keyof SessionrpeGetScaleResponses];

export type SessionrpeCreateLogData = {
    body: SessionRpeCreate;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/session-rpe/logs';
};

export type SessionrpeCreateLogErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type SessionrpeCreateLogError = SessionrpeCreateLogErrors[keyof SessionrpeCreateLogErrors];

export type SessionrpeCreateLogResponses = {
    /**
     * Successful Response
     */
    201: SessionRpeResponse;
};

export type SessionrpeCreateLogResponse = SessionrpeCreateLogResponses[keyof SessionrpeCreateLogResponses];

export type SessionrpeMeTodayData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * On Date
         */
        on_date?: string | null;
    };
    url: '/api/v1/session-rpe/me/today';
};

export type SessionrpeMeTodayErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type SessionrpeMeTodayError = SessionrpeMeTodayErrors[keyof SessionrpeMeTodayErrors];

export type SessionrpeMeTodayResponses = {
    /**
     * Successful Response
     */
    200: SessionRpeTodayStatus;
};

export type SessionrpeMeTodayResponse = SessionrpeMeTodayResponses[keyof SessionrpeMeTodayResponses];

export type SessionrpeMeHistoryData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit Days
         */
        limit_days?: number;
    };
    url: '/api/v1/session-rpe/me/history';
};

export type SessionrpeMeHistoryErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type SessionrpeMeHistoryError = SessionrpeMeHistoryErrors[keyof SessionrpeMeHistoryErrors];

export type SessionrpeMeHistoryResponses = {
    /**
     * Successful Response
     */
    200: SessionRpeHistoryResponse;
};

export type SessionrpeMeHistoryResponse = SessionrpeMeHistoryResponses[keyof SessionrpeMeHistoryResponses];

export type SessionrpeAthleteTodayData = {
    body?: never;
    headers?: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: {
        /**
         * On Date
         */
        on_date?: string | null;
    };
    url: '/api/v1/session-rpe/athletes/{user_id}/today';
};

export type SessionrpeAthleteTodayErrors = {
    /**
     * Requete invalide
     */
    400: ErrorDetail;
    /**
     * Non authentifie (JWT manquant ou invalide)
     */
    401: ErrorDetail;
    /**
     * Interdit (permissions / consentement)
     */
    403: ErrorDetail;
    /**
     * Ressource introuvable
     */
    404: ErrorDetail;
    /**
     * Conflit (doublon, etat incompatible)
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Trop de requetes (rate limit)
     */
    429: ErrorDetail;
};

export type SessionrpeAthleteTodayError = SessionrpeAthleteTodayErrors[keyof SessionrpeAthleteTodayErrors];

export type SessionrpeAthleteTodayResponses = {
    /**
     * Successful Response
     */
    200: SessionRpeTodayStatus;
};

export type SessionrpeAthleteTodayResponse = SessionrpeAthleteTodayResponses[keyof SessionrpeAthleteTodayResponses];

export type HealthHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthCheckResponse = HealthHealthCheckResponses[keyof HealthHealthCheckResponses];
